# Generated by Django 5.2.4 on 2025-08-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
