# Generated by Django 5.2.4 on 2025-08-04 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_food_stock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food',
            new_name='Menu',
        ),
    ]
